#!/usr/bin/env python3
"""
CAN Bus Binary Log Decoder
==========================
Decodes binary CAN log files generated by the ESP32 MiniGauge firmware into:
  1. Vector ASC files (.asc) - compatible with Vector CANoe, CANalyzer, SavvyCAN, etc.
  2. Decoded CSV files (.csv) - message-by-message log with physical signal values.
  3. (Optional) Flat signals CSV (_signals.csv) - ideal for plotting time series.

Binary record layout (16 bytes, packed little-endian, from main/logging.cpp):
    uint32_t timestamp; // 4 bytes (ms uptime)
    uint16_t id;        // 2 bytes (CAN arbitration ID)
    uint8_t  dlc;       // 1 byte  (data length code, 0-8)
    uint8_t  data[8];   // 8 bytes (payload data)
    uint8_t  padding;   // 1 byte  (padding to 16 bytes)
"""

import sys
import os
import struct
import glob
import re
import json
from pathlib import Path
from datetime import datetime, timezone
import argparse
from typing import Dict, List, Optional, Tuple, Any

RECORD_STRUCT = "<IHB8sx"
RECORD_SIZE = 16


# ---------------------------------------------------------------------------
# Built-in Lightweight DBC Database
# ---------------------------------------------------------------------------
class SignalDef:
    def __init__(
        self,
        name: str,
        mux: Optional[str],
        start_bit: int,
        bit_len: int,
        is_intel: bool,
        is_signed: bool,
        factor: float,
        offset: float,
        min_val: float,
        max_val: float,
        unit: str,
        valtype: int = 0,
        choices: Optional[Dict[int, str]] = None,
    ):
        self.name = name
        self.mux = mux  # 'M' for multiplexor, 'm<N>' for multiplexed, None for standard
        self.start_bit = start_bit
        self.bit_len = bit_len
        self.is_intel = is_intel
        self.is_signed = is_signed
        self.factor = factor
        self.offset = offset
        self.min_val = min_val
        self.max_val = max_val
        self.unit = unit
        self.valtype = valtype  # 0: int, 1: float32, 2: float64
        self.choices = choices or {}

    def decode_raw(self, payload: bytes) -> int:
        """Extracts raw integer bits from payload according to byte order."""
        if self.is_intel:
            val_int = int.from_bytes(payload, "little")
            return (val_int >> self.start_bit) & ((1 << self.bit_len) - 1)
        else:
            # Motorola (Big Endian) sequential bit extraction
            val = 0
            cur_bit = self.start_bit
            for _ in range(self.bit_len):
                byte_idx = cur_bit // 8
                bit_in_byte = cur_bit % 8
                if byte_idx < len(payload):
                    bit = (payload[byte_idx] >> bit_in_byte) & 1
                else:
                    bit = 0
                val = (val << 1) | bit
                if bit_in_byte == 0:
                    cur_bit = (byte_idx + 2) * 8 - 1
                else:
                    cur_bit -= 1
            return val

    def decode(self, payload: bytes) -> Tuple[Any, Optional[str]]:
        """Decodes raw bits into physical value and optional named enum choice."""
        raw = self.decode_raw(payload)

        # Signed conversion if not float
        if self.is_signed and not self.valtype:
            if raw & (1 << (self.bit_len - 1)):
                raw -= (1 << self.bit_len)

        # Float handling
        if self.valtype == 1:  # 32-bit float
            raw_bytes = (raw & 0xFFFFFFFF).to_bytes(4, "little")
            raw_float = struct.unpack("<f", raw_bytes)[0]
            phys = raw_float * self.factor + self.offset
        elif self.valtype == 2:  # 64-bit double
            raw_bytes = (raw & 0xFFFFFFFFFFFFFFFF).to_bytes(8, "little")
            raw_double = struct.unpack("<d", raw_bytes)[0]
            phys = raw_double * self.factor + self.offset
        else:
            phys = raw * self.factor + self.offset

        # Round clean floats or preserve integer
        if isinstance(phys, float):
            if phys.is_integer():
                phys = int(phys)
            else:
                phys = round(phys, 5)

        named = self.choices.get(int(raw))
        return phys, named


class MessageDef:
    def __init__(self, msg_id: int, name: str, dlc: int, sender: str):
        self.msg_id = msg_id
        self.name = name
        self.dlc = dlc
        self.sender = sender
        self.signals: List[SignalDef] = []
        self.mux_signal: Optional[SignalDef] = None

    def add_signal(self, sig: SignalDef):
        self.signals.append(sig)
        if sig.mux == "M":
            self.mux_signal = sig

    def decode(self, payload: bytes) -> Dict[str, Dict[str, Any]]:
        # Pad payload to at least 8 bytes for bit extraction
        if len(payload) < 8:
            payload = payload.ljust(8, b"\x00")

        # Determine multiplexor value if present
        mux_val = None
        if self.mux_signal:
            mux_val = self.mux_signal.decode_raw(payload)

        results = {}
        for sig in self.signals:
            if sig.mux and sig.mux != "M":
                try:
                    expected_mux = int(sig.mux[1:])
                    if mux_val != expected_mux:
                        continue
                except ValueError:
                    pass

            phys_val, choice_name = sig.decode(payload)
            results[sig.name] = {
                "value": phys_val,
                "unit": sig.unit,
                "choice": choice_name,
            }
        return results


class DbcDatabase:
    def __init__(self, filepath: str):
        self.filepath = filepath
        self.messages: Dict[int, MessageDef] = {}
        self._parse(filepath)

    def _parse(self, filepath: str):
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        # 1. Parse SIG_VALTYPE_
        valtype_re = re.compile(
            r"^SIG_VALTYPE_\s+(\d+)\s+(\w+)\s*:\s*(\d+)\s*;", re.MULTILINE
        )
        valtypes: Dict[Tuple[int, str], int] = {}
        for m in valtype_re.finditer(content):
            valtypes[(int(m.group(1)), m.group(2))] = int(m.group(3))

        # 2. Parse VAL_ enum tables
        val_re = re.compile(r"^VAL_\s+(\d+)\s+(\w+)\s+(.+);", re.MULTILINE)
        val_entry_re = re.compile(r'(\d+)\s+"([^"]*)"')
        val_choices: Dict[Tuple[int, str], Dict[int, str]] = {}
        for m in val_re.finditer(content):
            msg_id = int(m.group(1))
            sig_name = m.group(2)
            entries = val_entry_re.findall(m.group(3))
            val_choices[(msg_id, sig_name)] = {int(k): v for k, v in entries}

        # 3. Parse BO_ and SG_
        sg_re = re.compile(
            r'SG_\s+(\w+)\s*(?:(M|m\d+))?\s*:\s*(\d+)\|(\d+)@([01])([+-])\s+\(([-0-9.eE+]+),([-0-9.eE+]+)\)\s+\[([-0-9.eE+]+)\|([-0-9.eE+]+)\]\s+\"([^\"]*)\"'
        )

        current_msg: Optional[MessageDef] = None
        for line in content.splitlines():
            stripped = line.strip()
            if line.startswith("BO_ "):
                parts = line.split()
                if len(parts) >= 5:
                    msg_id = int(parts[1])
                    name = parts[2].rstrip(":")
                    dlc = int(parts[3])
                    sender = parts[4]
                    current_msg = MessageDef(msg_id, name, dlc, sender)
                    self.messages[msg_id] = current_msg
            elif stripped.startswith("SG_ ") and current_msg is not None:
                m = sg_re.search(stripped)
                if m:
                    sig_name = m.group(1)
                    mux = m.group(2)
                    start_bit = int(m.group(3))
                    bit_len = int(m.group(4))
                    is_intel = m.group(5) == "1"
                    is_signed = m.group(6) == "-"
                    factor = float(m.group(7))
                    offset = float(m.group(8))
                    min_val = float(m.group(9))
                    max_val = float(m.group(10))
                    unit = m.group(11)

                    valtype = valtypes.get((current_msg.msg_id, sig_name), 0)
                    choices = val_choices.get((current_msg.msg_id, sig_name), {})

                    sig = SignalDef(
                        name=sig_name,
                        mux=mux,
                        start_bit=start_bit,
                        bit_len=bit_len,
                        is_intel=is_intel,
                        is_signed=is_signed,
                        factor=factor,
                        offset=offset,
                        min_val=min_val,
                        max_val=max_val,
                        unit=unit,
                        valtype=valtype,
                        choices=choices,
                    )
                    current_msg.add_signal(sig)

    def get_message(self, msg_id: int) -> Optional[MessageDef]:
        return self.messages.get(msg_id)


# ---------------------------------------------------------------------------
# Binary Log Reader
# ---------------------------------------------------------------------------
class CanFrame:
    def __init__(
        self,
        timestamp_ms: int,
        time_rel_s: float,
        can_id: int,
        dlc: int,
        data: bytes,
    ):
        self.timestamp_ms = timestamp_ms
        self.time_rel_s = time_rel_s
        self.can_id = can_id
        self.dlc = dlc
        self.data = data


def read_bin_file(filepath: Path) -> List[CanFrame]:
    """Reads and parses a 16-byte packed binary log file."""
    with open(filepath, "rb") as f:
        raw_data = f.read()

    file_len = len(raw_data)
    if file_len == 0:
        return []

    record_count = file_len // RECORD_SIZE
    trailing = file_len % RECORD_SIZE
    if trailing != 0:
        print(f"  [!] Warning: {filepath.name} has {trailing} trailing bytes ignored")

    frames: List[CanFrame] = []
    first_ts: Optional[int] = None

    for i in range(record_count):
        chunk = raw_data[i * RECORD_SIZE : (i + 1) * RECORD_SIZE]
        ts_ms, can_id, dlc, payload = struct.unpack(RECORD_STRUCT, chunk)

        if first_ts is None:
            first_ts = ts_ms

        time_rel_s = max(0.0, (ts_ms - first_ts) / 1000.0)
        actual_len = min(dlc, 8)
        actual_data = payload[:actual_len]

        frames.append(CanFrame(ts_ms, time_rel_s, can_id, dlc, actual_data))

    return frames


# ---------------------------------------------------------------------------
# Exporters
# ---------------------------------------------------------------------------
def export_asc(frames: List[CanFrame], out_path: Path, ref_time: datetime):
    """Exports CAN frames to Vector CANoe / CANalyzer ASCII format (.asc)."""
    date_str = ref_time.strftime("%a %b %d %I:%M:%S %p %Y")

    with open(out_path, "w", encoding="ascii") as f:
        f.write(f"date {date_str}\n")
        f.write("base hex  timestamps absolute\n")
        f.write("internal events logged\n")
        f.write("// version 8.0.0\n")
        f.write(f"Begin Triggerblock {date_str}\n")

        for frame in frames:
            hex_bytes = " ".join(f"{b:02X}" for b in frame.data)
            f.write(
                f"{frame.time_rel_s:10.6f} 1  {frame.can_id:<15X} Rx   d {frame.dlc} {hex_bytes}\n"
            )

        f.write("End Triggerblock\n")


def export_csv(frames: List[CanFrame], db: DbcDatabase, out_path: Path):
    """Exports CAN frames to a CSV file with decoded physical signals."""
    import csv

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp_ms",
            "time_s",
            "can_id",
            "can_id_dec",
            "message_name",
            "dlc",
            "data_hex",
            "signals",
            "signals_json",
        ])

        for frame in frames:
            msg_def = db.get_message(frame.can_id)
            if msg_def:
                msg_name = msg_def.name
                decoded = msg_def.decode(frame.data)
                sig_parts = []
                sig_dict = {}
                for sig_name, info in decoded.items():
                    val = info["value"]
                    unit = f" {info['unit']}" if info["unit"] else ""
                    choice = f" ({info['choice']})" if info["choice"] else ""
                    sig_parts.append(f"{sig_name}={val}{unit}{choice}")
                    sig_dict[sig_name] = (
                        {"value": val, "unit": info["unit"]}
                        if info["unit"]
                        else {"value": val}
                    )
                    if info["choice"]:
                        sig_dict[sig_name]["state"] = info["choice"]

                signals_str = "; ".join(sig_parts)
                signals_json = json.dumps(sig_dict)
            else:
                msg_name = f"UNKNOWN_0x{frame.can_id:03X}"
                signals_str = ""
                signals_json = "{}"

            writer.writerow([
                frame.timestamp_ms,
                f"{frame.time_rel_s:.6f}",
                f"0x{frame.can_id:03X}",
                frame.can_id,
                msg_name,
                frame.dlc,
                frame.data.hex().upper(),
                signals_str,
                signals_json,
            ])


def export_signals_csv(frames: List[CanFrame], db: DbcDatabase, out_path: Path):
    """Exports a flat, tidy signal-by-signal time-series CSV table."""
    import csv

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp_ms",
            "time_s",
            "can_id",
            "message_name",
            "signal_name",
            "value",
            "unit",
            "state",
        ])

        for frame in frames:
            msg_def = db.get_message(frame.can_id)
            if not msg_def:
                continue
            decoded = msg_def.decode(frame.data)
            for sig_name, info in decoded.items():
                writer.writerow([
                    frame.timestamp_ms,
                    f"{frame.time_rel_s:.6f}",
                    f"0x{frame.can_id:03X}",
                    msg_def.name,
                    sig_name,
                    info["value"],
                    info["unit"],
                    info["choice"] or "",
                ])


def export_wide_csv(frames: List[CanFrame], db: DbcDatabase, out_path: Path):
    """Exports a wide matrix CSV where each signal is its own column."""
    import csv

    all_signals = []
    seen_signals = set()
    for msg in db.messages.values():
        for sig in msg.signals:
            if sig.name not in seen_signals:
                seen_signals.add(sig.name)
                all_signals.append(sig.name)

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        headers = [
            "timestamp_ms",
            "time_s",
            "can_id",
            "message_name",
        ] + all_signals
        writer.writerow(headers)

        for frame in frames:
            msg_def = db.get_message(frame.can_id)
            msg_name = msg_def.name if msg_def else f"UNKNOWN_0x{frame.can_id:03X}"
            decoded = msg_def.decode(frame.data) if msg_def else {}

            row = [
                frame.timestamp_ms,
                f"{frame.time_rel_s:.6f}",
                f"0x{frame.can_id:03X}",
                msg_name,
            ]
            for sig_name in all_signals:
                if sig_name in decoded:
                    row.append(decoded[sig_name]["value"])
                else:
                    row.append("")
            writer.writerow(row)


# ---------------------------------------------------------------------------
# Main Routine
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Decode ESP32 CAN bus binary logs (.bin) into CSV and ASC."
    )
    parser.add_argument(
        "inputs",
        nargs="*",
        help="Input .bin log files (defaults to all log_*.bin files in decoder directory)",
    )
    parser.add_argument(
        "--dbc",
        "-d",
        help="Path to DBC database file (defaults to binocan.dbc or first *.dbc)",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        help="Output directory (defaults to same folder as input files)",
    )
    parser.add_argument(
        "--asc-only", action="store_true", help="Generate only Vector .asc files"
    )
    parser.add_argument(
        "--csv-only", action="store_true", help="Generate only decoded .csv files"
    )
    parser.add_argument(
        "--signals",
        "-s",
        action="store_true",
        help="Also generate flat _signals.csv time series table",
    )
    parser.add_argument(
        "--wide",
        "-w",
        action="store_true",
        help="Also generate wide _wide.csv time series matrix",
    )

    args = parser.parse_args()

    # Find script dir
    script_dir = Path(__file__).resolve().parent

    # 1. Resolve DBC
    dbc_path = None
    if args.dbc:
        dbc_path = Path(args.dbc)
    else:
        # Auto-find in script_dir or current working directory
        default_candidates = [
            script_dir / "binocan.dbc",
            Path("binocan.dbc"),
            *script_dir.glob("*.dbc"),
            *Path(".").glob("*.dbc"),
        ]
        for cand in default_candidates:
            if cand.is_file():
                dbc_path = cand
                break

    if not dbc_path or not dbc_path.is_file():
        print("[-] Error: Could not locate DBC database file. Specify one with --dbc <path.dbc>")
        sys.exit(1)

    print(f"[+] Loading DBC database: {dbc_path.name}")
    db = DbcDatabase(str(dbc_path))
    print(f"    Loaded {len(db.messages)} message definitions from DBC.")

    # 2. Resolve input files
    if args.inputs:
        bin_files = []
        for item in args.inputs:
            p = Path(item)
            if p.is_file():
                bin_files.append(p)
            elif "*" in item or "?" in item:
                bin_files.extend(Path(f) for f in glob.glob(item))
            else:
                print(f"[-] Warning: input path not found: {item}")
    else:
        # Default: search in script dir or cwd
        bin_files = sorted(script_dir.glob("log_*.bin"))
        if not bin_files:
            bin_files = sorted(Path(".").glob("log_*.bin"))

    if not bin_files:
        print("[-] Error: No .bin log files found.")
        sys.exit(1)

    print(f"[+] Found {len(bin_files)} log file(s) to process.")

    # 3. Process each log file
    success_count = 0
    for bf in bin_files:
        print(f"\n---> Processing: {bf.name} ({bf.stat().st_size:,} bytes)")

        out_dir = Path(args.output_dir) if args.output_dir else bf.parent
        out_dir.mkdir(parents=True, exist_ok=True)
        base_name = bf.stem

        frames = read_bin_file(bf)
        if not frames:
            print(f"     [i] File is empty (0 frames). Skipped.")
            continue

        duration_s = frames[-1].time_rel_s if frames else 0.0
        print(f"     Parsed {len(frames):,} frames (duration: {duration_s:.2f}s).")

        ref_time = datetime.fromtimestamp(bf.stat().st_mtime, tz=timezone.utc)
        # If mtime is default FAT epoch (Jan 1980), use current time
        if ref_time.year <= 1980:
            ref_time = datetime.now()

        # ASC output
        if not args.csv_only:
            asc_file = out_dir / f"{base_name}.asc"
            export_asc(frames, asc_file, ref_time)
            print(f"     [✓] Wrote ASC:  {asc_file.name}")

        # CSV output
        if not args.asc_only:
            csv_file = out_dir / f"{base_name}.csv"
            export_csv(frames, db, csv_file)
            print(f"     [✓] Wrote CSV:  {csv_file.name}")

        # Optional flat signals CSV
        if args.signals:
            sig_csv_file = out_dir / f"{base_name}_signals.csv"
            export_signals_csv(frames, db, sig_csv_file)
            print(f"     [✓] Wrote Flat Signals: {sig_csv_file.name}")

        # Optional wide signals CSV
        if args.wide:
            wide_csv_file = out_dir / f"{base_name}_wide.csv"
            export_wide_csv(frames, db, wide_csv_file)
            print(f"     [✓] Wrote Wide Matrix:  {wide_csv_file.name}")

        success_count += 1

    print(f"\n[✓] Finished decoding {success_count}/{len(bin_files)} non-empty log file(s).")


if __name__ == "__main__":
    main()

