#!/usr/bin/env python3
"""
CAN Bus Binary Log Decoder
==========================
Decodes binary CAN log files generated by the ESP32 MiniGauge firmware into:
  1. Vector ASC files (.asc) - compatible with Vector CANoe, CANalyzer, SavvyCAN, etc.
  2. Decoded CSV files (.csv) - message-by-message log with physical signal values.
  3. (Optional) Flat signals CSV (_signals.csv) - ideal for plotting time series.

Binary record layout (16 bytes, packed little-endian, from main/logging.cpp):
    uint32_t timestamp; // 4 bytes (ms uptime)
    uint16_t id;        // 2 bytes (CAN arbitration ID)
    uint8_t  dlc;       // 1 byte  (data length code, 0-8)
    uint8_t  data[8];   // 8 bytes (payload data)
    uint8_t  padding;   // 1 byte  (padding to 16 bytes)
"""

import sys
import os
import struct
import glob
import re
import json
from pathlib import Path
from datetime import datetime, timezone
import argparse
from typing import Dict, List, Optional, Tuple, Any

# Ensure decoder directory is on sys.path for common imports
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from common import (
    CanFrame,
    read_bin_file,
    DbcDatabase,
    SignalDef,
    MessageDef,
    RECORD_STRUCT,
    RECORD_SIZE,
)



# ---------------------------------------------------------------------------
# Exporters
# ---------------------------------------------------------------------------
def export_asc(frames: List[CanFrame], out_path: Path, ref_time: datetime):
    """Exports CAN frames to Vector CANoe / CANalyzer ASCII format (.asc)."""
    date_str = ref_time.strftime("%a %b %d %I:%M:%S %p %Y")

    with open(out_path, "w", encoding="ascii") as f:
        f.write(f"date {date_str}\n")
        f.write("base hex  timestamps absolute\n")
        f.write("internal events logged\n")
        f.write("// version 8.0.0\n")
        f.write(f"Begin Triggerblock {date_str}\n")

        for frame in frames:
            hex_bytes = " ".join(f"{b:02X}" for b in frame.data)
            f.write(
                f"{frame.time_rel_s:10.6f} 1  {frame.can_id:<15X} Rx   d {frame.dlc} {hex_bytes}\n"
            )

        f.write("End Triggerblock\n")


def export_csv(frames: List[CanFrame], db: DbcDatabase, out_path: Path):
    """Exports CAN frames to a CSV file with decoded physical signals."""
    import csv

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp_ms",
            "time_s",
            "can_id",
            "can_id_dec",
            "message_name",
            "dlc",
            "data_hex",
            "signals",
            "signals_json",
        ])

        for frame in frames:
            msg_def = db.get_message(frame.can_id)
            if msg_def:
                msg_name = msg_def.name
                decoded = msg_def.decode(frame.data)
                sig_parts = []
                sig_dict = {}
                for sig_name, info in decoded.items():
                    val = info["value"]
                    unit = f" {info['unit']}" if info["unit"] else ""
                    choice = f" ({info['choice']})" if info["choice"] else ""
                    sig_parts.append(f"{sig_name}={val}{unit}{choice}")
                    sig_dict[sig_name] = (
                        {"value": val, "unit": info["unit"]}
                        if info["unit"]
                        else {"value": val}
                    )
                    if info["choice"]:
                        sig_dict[sig_name]["state"] = info["choice"]

                signals_str = "; ".join(sig_parts)
                signals_json = json.dumps(sig_dict)
            else:
                msg_name = f"UNKNOWN_0x{frame.can_id:03X}"
                signals_str = ""
                signals_json = "{}"

            writer.writerow([
                frame.timestamp_ms,
                f"{frame.time_rel_s:.6f}",
                f"0x{frame.can_id:03X}",
                frame.can_id,
                msg_name,
                frame.dlc,
                frame.data.hex().upper(),
                signals_str,
                signals_json,
            ])


def export_signals_csv(frames: List[CanFrame], db: DbcDatabase, out_path: Path):
    """Exports a flat, tidy signal-by-signal time-series CSV table."""
    import csv

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp_ms",
            "time_s",
            "can_id",
            "message_name",
            "signal_name",
            "value",
            "unit",
            "state",
        ])

        for frame in frames:
            msg_def = db.get_message(frame.can_id)
            if not msg_def:
                continue
            decoded = msg_def.decode(frame.data)
            for sig_name, info in decoded.items():
                writer.writerow([
                    frame.timestamp_ms,
                    f"{frame.time_rel_s:.6f}",
                    f"0x{frame.can_id:03X}",
                    msg_def.name,
                    sig_name,
                    info["value"],
                    info["unit"],
                    info["choice"] or "",
                ])


def export_wide_csv(frames: List[CanFrame], db: DbcDatabase, out_path: Path):
    """Exports a wide matrix CSV where each signal is its own column."""
    import csv

    all_signals = []
    seen_signals = set()
    for msg in db.messages.values():
        for sig in msg.signals:
            if sig.name not in seen_signals:
                seen_signals.add(sig.name)
                all_signals.append(sig.name)

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        headers = [
            "timestamp_ms",
            "time_s",
            "can_id",
            "message_name",
        ] + all_signals
        writer.writerow(headers)

        for frame in frames:
            msg_def = db.get_message(frame.can_id)
            msg_name = msg_def.name if msg_def else f"UNKNOWN_0x{frame.can_id:03X}"
            decoded = msg_def.decode(frame.data) if msg_def else {}

            row = [
                frame.timestamp_ms,
                f"{frame.time_rel_s:.6f}",
                f"0x{frame.can_id:03X}",
                msg_name,
            ]
            for sig_name in all_signals:
                if sig_name in decoded:
                    row.append(decoded[sig_name]["value"])
                else:
                    row.append("")
            writer.writerow(row)


# ---------------------------------------------------------------------------
# Main Routine
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Decode ESP32 CAN bus binary logs (.bin) into CSV and ASC."
    )
    parser.add_argument(
        "inputs",
        nargs="*",
        help="Input .bin log files (defaults to all *.bin files in decoder directory)",
    )
    parser.add_argument(
        "--dbc",
        "-d",
        help="Path to DBC database file (defaults to binocan.dbc or first *.dbc)",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        help="Output directory (defaults to same folder as input files)",
    )
    parser.add_argument(
        "--asc-only", action="store_true", help="Generate only Vector .asc files"
    )
    parser.add_argument(
        "--csv-only", action="store_true", help="Generate only decoded .csv files"
    )
    parser.add_argument(
        "--signals",
        "-s",
        action="store_true",
        help="Also generate flat _signals.csv time series table",
    )
    parser.add_argument(
        "--wide",
        "-w",
        action="store_true",
        help="Also generate wide _wide.csv time series matrix",
    )

    args = parser.parse_args()

    # Find script dir
    script_dir = Path(__file__).resolve().parent

    # 1. Resolve DBC
    dbc_path = None
    if args.dbc:
        dbc_path = Path(args.dbc)
    else:
        # Auto-find in script_dir or current working directory
        default_candidates = [
            script_dir / "binocan.dbc",
            Path("binocan.dbc"),
            *script_dir.glob("*.dbc"),
            *Path(".").glob("*.dbc"),
        ]
        for cand in default_candidates:
            if cand.is_file():
                dbc_path = cand
                break

    if not dbc_path or not dbc_path.is_file():
        print("[-] Error: Could not locate DBC database file. Specify one with --dbc <path.dbc>")
        sys.exit(1)

    print(f"[+] Loading DBC database: {dbc_path.name}")
    db = DbcDatabase(str(dbc_path))
    print(f"    Loaded {len(db.messages)} message definitions from DBC.")

    # 2. Resolve input files
    if args.inputs:
        bin_files = []
        for item in args.inputs:
            p = Path(item)
            if p.is_file():
                bin_files.append(p)
            elif "*" in item or "?" in item:
                bin_files.extend(Path(f) for f in glob.glob(item))
            else:
                print(f"[-] Warning: input path not found: {item}")
    else:
        # Default: search in script dir or cwd for all *.bin files
        def _nat_key(p: Path):
            return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', p.name)]

        bin_files = sorted([p for p in script_dir.glob("*.bin") if p.is_file()], key=_nat_key)
        if not bin_files:
            bin_files = sorted([p for p in Path(".").glob("*.bin") if p.is_file()], key=_nat_key)

    if not bin_files:
        print("[-] Error: No .bin log files found.")
        sys.exit(1)

    print(f"[+] Found {len(bin_files)} log file(s) to process.")

    # 3. Process each log file
    success_count = 0
    for bf in bin_files:
        print(f"\n---> Processing: {bf.name} ({bf.stat().st_size:,} bytes)")

        out_dir = Path(args.output_dir) if args.output_dir else bf.parent
        out_dir.mkdir(parents=True, exist_ok=True)
        base_name = bf.stem

        frames = read_bin_file(bf)
        if not frames:
            print(f"     [i] File is empty (0 frames). Skipped.")
            continue

        duration_s = frames[-1].time_rel_s if frames else 0.0
        print(f"     Parsed {len(frames):,} frames (duration: {duration_s:.2f}s).")

        ref_time = datetime.fromtimestamp(bf.stat().st_mtime, tz=timezone.utc)
        # If mtime is default FAT epoch (Jan 1980), use current time
        if ref_time.year <= 1980:
            ref_time = datetime.now()

        # ASC output
        if not args.csv_only:
            asc_file = out_dir / f"{base_name}.asc"
            export_asc(frames, asc_file, ref_time)
            print(f"     [✓] Wrote ASC:  {asc_file.name}")

        # CSV output
        if not args.asc_only:
            csv_file = out_dir / f"{base_name}.csv"
            export_csv(frames, db, csv_file)
            print(f"     [✓] Wrote CSV:  {csv_file.name}")

        # Optional flat signals CSV
        if args.signals:
            sig_csv_file = out_dir / f"{base_name}_signals.csv"
            export_signals_csv(frames, db, sig_csv_file)
            print(f"     [✓] Wrote Flat Signals: {sig_csv_file.name}")

        # Optional wide signals CSV
        if args.wide:
            wide_csv_file = out_dir / f"{base_name}_wide.csv"
            export_wide_csv(frames, db, wide_csv_file)
            print(f"     [✓] Wrote Wide Matrix:  {wide_csv_file.name}")

        success_count += 1

    print(f"\n[✓] Finished decoding {success_count}/{len(bin_files)} non-empty log file(s).")


if __name__ == "__main__":
    main()

